RANDOM_STATE = 42
TOKENIZER_MODEL = "ufal/robeczech-base"
ENCODER_MODEL = "ufal/robeczech-base"

FINETUNED_CHECKPOINT = "ufalrobeczech-base_20221127-171131"
FINETUNED_EPOCH = 3
FINETUNED_DATASET = "mall"
